export const SIGNIN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGN_IN_FAILURE';

export const STORE_LIST_REQUEST = 'STORE_LIST_REQUEST';
export const STORE_LIST_SUCCESS = 'STORE_LIST_SUCCESS';
export const STORE_LIST_FAILURE = 'STORE_LIST_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE';

export const PRESCRIPTION_ORDER_REQUEST = 'PRESCRIPTION_ORDER_REQUEST';
export const PRESCRIPTION_ORDER_SUCCESS = 'PRESCRIPTION_ORDER_SUCCESS';
export const PRESCRIPTION_ORDER_FAILURE = 'PRESCRIPTION_ORDER_FAILURE';

export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST';
export const SERVICE_LIST_SUCCESS = 'SERVICE_LIST_SUCCESS';
export const SERVICE_LIST_FAILURE = 'SERVICE_LIST_FAILURE';

export const SERVICE_ORDER_REQUEST = 'SERVICE_ORDER_REQUEST';
export const SERVICE_ORDER_SUCCESS = 'SERVICE_ORDER_SUCCESS';
export const SERVICE_ORDER_FAILURE = 'SERVICE_ORDER_FAILURE';

export const MEDICATION_LIST_REQUEST = 'MEDICATION_LIST_REQUEST';
export const MEDICATION_LIST_SUCCESS = 'MEDICATION_LIST_SUCCESS';
export const MEDICATION_LIST_FAILURE = 'MEDICATION_LIST_FAILURE';

export const MEDICATION_REMINDER_REQUEST = 'MEDICATION_REMINDER_REQUEST';
export const MEDICATION_REMINDER_SUCCESS = 'MEDICATION_REMINDER_SUCCESS';
export const MEDICATION_REMINDER_FAILURE = 'MEDICATION_REMINDER_FAILURE';

export const EDIT_MEDICATION_REQUEST = 'EDIT_MEDICATION_REQUEST';
export const EDIT_MEDICATION_SUCCESS = 'EDIT_MEDICATION_SUCCESS';
export const EDIT_MEDICATION_FAILURE = 'EDIT_MEDICATION_FAILURE';

export const DELETE_MEDICATION_REQUEST = 'DELETE_MEDICATION_REQUEST';
export const DELETE_MEDICATION_SUCCESS = 'DELETE_MEDICATION_SUCCESS';
export const DELETE_MEDICATION_FAILURE = 'DELETE_MEDICATION_FAILURE';

export const MY_PHARMACY_REQUEST = 'MY_PHARMACY_REQUEST';
export const MY_PHARMACY_SUCCESS = 'MY_PHARMACY_SUCCESS';
export const MY_PHARMACY_FAILURE = 'MY_PHARMACY_FAILURE';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

export const CALL_NOW_REQUEST = 'CALL_NOW_REQUEST';
export const CALL_NOW_SUCCESS = 'CALL_NOW_SUCCESS';
export const CALL_NOW_FAILURE = 'CALL_NOW_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
