const string = {
  Proceed: 'Proceed',
  appName: 'Phelans',
  welcomeText: 'Welcome to \nPhelans Family Pharmacy',
  callNow: 'Call now',
  welcome: 'Welcome',
  addMore: 'Add More',
  finish: 'Finish',
  forgotPassword: 'Forgot your password?',
  Login: 'Log in',
  Signin: 'Sign in',
  Register: 'Register',
  Email_address: 'Email address',
  Enteryouremailaddress: 'Enter your email address',
  Forgot_Password: 'Forgot Password',
  addMoreInfo:
    'You have successfully registered. If you want to add family members to your profile, please click add more.',
  forgotPasswordResent: 'You have successfully send you email',
  addUserSuccessInfo:
    'Patient successfully added. if you want to add more family members to your profile, please click add more.',
  AddUser: 'Add User',
  AddPatient: 'Additional Patient',
  congratulations: 'Congratulations',
  or: 'Or',
  promotionInfo:
    "I would to like recieve Phelan's promotional messages & offers",
  submit: 'Submit',
  storeNameValidation: 'Please select the store name',
  emailValidation: 'Please enter email',
  notesValidation: 'Please enter notes',
  prescriptionValidation: 'Please enter prescription text',
  reminderTitleValidation: 'Please enter reminder title',
  collectionValidation: 'Please enter collection text',
  emailFormatValidation: 'Please enter valid email',
  passwordValidation: 'Please enter password',
  nameValidation: 'Please enter name',
  telephoneValidation: 'Please enter telephone',
  addressValidation: 'Please enter address',
  birthDateValidation: 'Please select birth date',
  dateValidation: 'Please select date',
  noteValidation: 'Please entet note',
  timeValidation: 'Please select time',
  inDevelopment: 'In Development',
  patientInfo: 'Patient Information',
  verifyPatientInfo: 'Please Verify Patient Name',
  selectPateint: 'Select Patient Name',
  next: 'Next',
  prescriptionManager: 'Prescription Manager',
  order: 'order',
  reminder: 'reminder',
  prescription: 'Prescription',
  bookAService: 'Book A service',
  medicineReminder: 'Medicine Reminder',
  myPharmacy: 'My Pharmacy',
  locator: 'Locator',
  user: 'User',
  orderPrescription: 'Order Prescription',
  prescription1:
    "Tell us when you would like to collect and if you don't need all your prescription items.",
  prescription2:
    'For repeats held on the file what items do you require? No photo required for repeats.',
  takePhoto: 'Take Photo',
  selectOption: 'Select Option',
  camera: 'Camera',
  gallery: 'Gallery',
  permissionGalleryInfo:
    'Please give photo gallery permission to upload picture of prescription',
  permissionCameraInfo:
    'Please give camera permission to take picture of prescription',
  somethingWentWrong: 'Something went wrong',
  ThankYou: 'Thank you !',
  ForYourOrder: 'For your order',
  ForYourService: 'For Your Service Booking',
  AnotherOrderPrescription: 'Would you like to make another order?',
  orderConfirmation: 'We have received your booking and it is being processed',
  yes: 'Yes',
  no: 'No',
  reminderExp: 'Reminder!',
  reminderInfo:
    'Please make sure to bring your original prescription when collecting unless we already hold it on file.',
  ok: 'OK',
  reorderReminder: 'Reorder reminder',
  reminderTitleQuestion: 'Which Prescription can we remind you of ?',
  reminderTitlePlaceholder: 'Reorder Reminder (optional)',
  setTime: 'Set Time',
  startDate: 'Start Date',
  setDate: 'Set Date',
  setFrequency: 'Set Frequency',
  save: 'Save',
  additionalNotes: 'Additional notes',
  bookYourService: 'Book Your Service',
  serviceName: 'Please select service',
  goBackHome: 'Go Back To Home',
  DDMMYY: 'DD/MM/YY',
  hhmmam: 'hh:mm am',
  clear: 'Clear',
  set: 'Set',
  yourSetReminders: 'Your Set Reminders',
  deleteReminderAlert: 'Are you sure want to remove this reminder',
  pharmacist: 'Supervising Pharmacist',
  phone: 'Phone',
  email: 'Email',
  storeServices: 'Store Services',
  openingHours: 'Opening Hours',
  na: 'N/A\n',
  mon: 'MON',
  tue: 'TUE',
  wed: 'WED',
  thu: 'THU',
  fri: 'FRI',
  sat: 'SAT',
  sun: 'SUN',
  edit: 'Edit',
  done: 'Done',
  profile: 'Profile',
  personalInfo: 'Your Personal Info',
};

export default string;
