const IMAGES = {
  ic_book_service: require('./ic_book_service.png'),
  ic_camera: require('./ic_camera.png'),
  ic_email: require('./ic_email.png'),
  ic_locator: require('./ic_locator.png'),
  ic_medicine_reminder: require('./ic_medicine_reminder.png'),
  ic_my_pharmacy: require('./ic_my_pharmacy.png'),
  ic_phone: require('./ic_phone.png'),
  ic_prescription: require('./ic_prescription.png'),
  ic_set_frequency: require('./ic_set_frequency.png'),
  ic_set_time: require('./ic_set_time.png'),
  ic_start_date: require('./ic_start_date.png'),
  ic_user: require('./ic_user.png'),
  ic_logo: require('./ic_logo.png'),
  ic_back: require('./ic_back.png'),
  ic_logout: require('./ic_logout.png'),
  ic_call: require('./ic_call.png'),
  ic_check: require('./ic_check.png'),
  ic_cancel: require('./ic_cancel.png'),
  ic_down: require('./ic_down.png'),
  ic_edit: require('./ic_edit.png'),
  ic_delete: require('./ic_delete.png'),
  ic_greeen_check: require('./ic_greeen_check.png'),
  ic_pin: require('./ic_pin.png'),
  ic_reminder: require('./ic_reminder.png'),
  ic_email_address: require('./ic_email_address.png'),
  ic_contact: require('./ic_contact.png'),
  ic_service: require('./ic_service.png'),
  ic_user_secondary: require('./ic_user_secondary.png'),
};
export default IMAGES;
