export const appRoutes = Object.freeze({
  Splash: 'Splash',
  PreAuth: 'PreAuth',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  Home: 'Home',
  Register: 'Register',
  AddUser: 'AddUser',
  PrescriptionManager: 'PrescriptionManager',
  OrderPrescription: 'OrderPrescription',
  ThankOrder: 'ThankOrder',
  PrescriptionReminder: 'PrescriptionReminder',
  BookAService: 'BookAService',
  ThankService: 'ThankService',
  MedicineReminder: 'MedicineReminder',
  Locator: 'Locator',
  MyPharmacy: 'MyPharmacy',
  User: 'User',
});
